#+title: Ada E7 Weekly Notes250223 Gr

* Session 1 (250203): Algorithms, Music, Poetry, Art
** Εκτός προγράμματος: Overture

Mozart // La clemenza di Tito
Bergen Nasjonale Opera
https://youtu.be/YWtS9BDu410?t=321

** [fn:1]Οι αλγόριθμοι, η ποίηση και η μουσική είναι αδέλφια

Παράδειγμα:

Μπαχ Σονάτα για βιολί και πλήκτρα αρ. 5 σε φα ελάσσονα, BWV 1018, 3ο μέρος: Adagio. Αφήγηση και διάλογος με αναφορές σε μεσαιωνικούς ύμνους.

*** Διάλογος
Το Adagio είναι σε ντο ελάσσονα (ή φα δοριανό). Είναι γραμμένο ως διπλός διάλογος. Τα δύο όργανα βρίσκονται σε διάλογο μεταξύ τους και ταυτόχρονα κάθε όργανο βρίσκεται σε διάλογο με τον εαυτό του!
- (α) Οι δύο ομιλητές του διαλόγου μιλούν ή τραγουδούν με αντίθετο διακριτό τρόπο: Το βιολί με ομοιόμορφους, σταθερά παλλόμενους κίονες σαν καρδιακούς παλμούς ή σαν αργό περπάτημα.  Το πιάνο από την άλλη μεριά σε κομψά ρέοντα άνθη τριπλών ημικύκλιων, όπως τα κύματα ή το τρεχούμενο νερό.
- (β) Ταυτόχρονα, κάθε μία από τις φωνές χωρίζεται επίσης σε δύο μέρη που συνομιλούν μεταξύ τους, με αντιθετικό τρόπο:
  - Το βιολί παίζει με διπλά στοπ, δηλαδή δύο νότες κάθε φορά: Οι δύο φωνές ξεκινούν τραγουδώντας απλώς μαζί σε αρμονία, αλλά κατά τη διάρκεια του κομματιού, η μία φωνή αρχίζει να απαντά στην άλλη φωνή σε μοτίβα 4 ή 8 νοτών.
  - Το πληκτρολόγιο παίζει έναν διάλογο μεταξύ του αριστερού και του δεξιού χεριού.  Το δεξί χέρι απαντά στο αριστερό χέρι φράση προς φράση.

*** Αναφορά στη μεσαιωνική υμνογραφία: Pange Lingua

Το ρυθμικό μοτίβο και η μελωδία του βιολιού είναι σαφώς δομημένα σε ομάδες των 16 νοτών με το διακριτό μετρικό μοτίβο των 8 ομάδων των 2 κτύπων σε μια κανονική σειρά τονισμένων - μη τονισμένων:
/ x / x / x / x / x / x / x / x / x / x / x / x
Αυτή η κανονική ροή τονισμένων - μη τονισμένων χτύπων δημιουργεί δύο σημασιολογικές συσχετίσεις:
1. Τακτικοί καρδιακοί παλμοί ή αναπνοή, η οποία η ομοιόμορφη και ελάχιστη μελωδική γραμμή υποδηλώνει ότι θα μπορούσε να συνδεθεί με το τραγούδι ή τον εσωτερικό διαλογισμό μιας προσευχής.
2. Περπάτημα με αργό και κανονικό ρυθμό.

Αυτό το μετρικό μοτίβο και η διάθεση προσευχής που προτείνει το σχήμα της μελωδίας ενισχύεται περαιτέρω από τη συσχέτιση με ένα χαρακτηριστικό μετρικό μοτίβο της λατινικής υμνολογίας.  Πρόκειται για το τροχαϊκό τετράμετρο και το στενά συνδεδεμένο με αυτό τροχαϊκό σεπτερνάριο https://en.wikipedia.org/wiki/Trochaic_septenarius. ένα μετρικό σχήμα 15 συλλαβών ελληνικής προέλευσης του 7ου αιώνα που χρησιμοποιείται ευρέως στη λατινική υμνογραφία.

| - u - x | - u - x || - u - x | - u - x | - u - |

ή (όπως χρησιμοποιείται στη ρωμαϊκή κωμωδία):

| - x - x | - x - x || - x - x | - u - |


*** Παραστάσεις/Παραδείγματα:

Bach Σονάτα για βιολί και πλήκτρα αρ. 5 σε φα ελάσσονα, BWV 1018, 3ο μέρος: Adagio
Ερμηνεία από τους Viktoria Mullova και Ottavio Dantone: https://www.youtube.com/watch?v=W_La_2WDmd8
Ερμηνεία από τους Andrew Manze και Richard Egarr: https://www.youtube.com/watch?v=UlxgxG6ab50 («Σονάτα σε φα ελάσσονα, BWV 1018: III. Adagio»)
Ερμηνεία με παρτιτούρα: https://youtu.be/eVemQvcLy64?t=747

*** Παρτιτούρες

https://imslp.org/wiki/6_Violin_Sonatas,_BWV_1014-1019_(Bach,_Johann_Sebastian)

*** Ερώτηση 1:

Τι σας υποδηλώνουν οι χειρονομίες στις δύο διαφορετικές φωνές του διαλόγου (βιολί και πλήκτρα);  Αν πρόκειται για τις φωνές δύο αφηγητών, ποιοι θα ήταν αυτοί οι αφηγητές και ποιοι θα ήταν οι χαρακτήρες και οι προσωπικότητές τους;

*** Ερώτηση 2:

Ποιο γνωστό ελληνικό ποίημα χρησιμοποιεί το ίδιο μέτρο με το «Pange Lingua».

*** Ερώτηση 3:

Υπάρχουν γνωστοί ελληνικοί χοροί που χρησιμοποιούν το ίδιο μέτρο με το «Pange Lingua»; Ποιοι;

*** Ερώτηση 4:

Συγκρίνετε το χαρακτήρα του μετρικού σχήματος του «Pange Lingua» με το αντίστοιχο μετρικό σχήμα με τον ίδιο αριθμό συλλαβών στην ελληνική δημοτική ποίηση.


** Ενότητα των Τεχνών: Η Μουσική είναι στην Ποίηση είναι στη Ζωγραφική

*** Παράδειγμα:

Κυκλικές μετρικές και μελωδικές δομές στην ινδική μουσική και στη δυτική μουσική.
Ουροβόρος στη μελωδία ostinato που συνοδεύει τα νοτιο-ινδικά τύμπανα, στο ρυθμό που κωδικοποιεί συλλαβές της ινδικής μουσικής, στα δυτικά κάλαντα, σε χορευτικές φόρμες όπως η Chaconne, η Passacaglia, η Ground, και σε μεγάλο αριθμό αφρικανικών και λατινοαμερικάνικων χορευτικών μορφών κ.λπ.

Το σύμβολο του κύκλου στη ζωγραφική Ζεν ως ουροβόρος. Το χαρακτηριστικό κυκλικό κίνητρο στη ζωγραφική Ζεν ονομάζεται Ensō (円相, «κυκλική μορφή») (https://en.wikipedia.org/wiki/Ensō). Το Ensō συνδέεται επίσης με 10 σχέδια σε συνδυασμό με 10 ποιήματα που χρησιμεύουν ως παρομοιώσεις για την πρακτική του διαλογισμού, γνωστά και ως οι Δέκα Ταύροι. https://en.wikipedia.org/wiki/Ten_Bulls.

*** Ερωτήσεις:
- Αποτελούν τα κυκλικά μοτίβα στα κάλαντα (και σε άλλη μουσική) στη Δύση συμβολική αναφορά στην κυκλική φύση του χρόνου;  Με ποιον τρόπο η χρήση τους σε συγκεκριμένες γιορτές υποδηλώνει κάτι τέτοιο;
- Πού αλλού υπάρχουν αναφορές και αναπαραστάσεις του κυκλικού χρόνου στις εικαστικές τέχνες, την ποίηση και τη μουσική;
- Ποια είναι η σημασία του κυκλικού χρόνου στο σύγχρονο πλαίσιο;

*** Αρχές αλγοριθμικής κατασκευής σε μουσικές δομές εκτός και εντός χρόνου

Η άνιση διαίρεση 7-5 του 12:
- Στο σχεδιασμό της διατονικής κλίμακας (βλ. επίσης πληκτρολόγιο πιάνου)
- Στη διαίρεση του μέτρου των 12 κτύπων σε ένα μοτίβο 7 κτύπων και ένα μοτίβο 5 κτύπων στην αφρικανική και αφροαμερικανική μουσική.

Παραδείγματα:

***** Martin Scherzinger: Μαθηματικά των ρυθμών των αφρικανικών χορών.
https://youtu.be/2TgFp76Rnig?t=303

***** Σόλι τάμπλα με συνοδεία κυκλικής μελωδίας

- Γυναίκα παίκτρια τάμπλα - Mitali Khargonkar Vinchurkar https://www.youtube.com/watch?v=dA6LeyfmE9E
- Mitali Khargonkar Vinchurkar ( Αφιέρωμα στον ustad Jahangeer Khan Sahab ) https://www.youtube.com/watch?v=12BUw_STDVc
- An offering to Abbaji Ustad Allarakha Kha Sahab By Mitali Khargonkar Vinchurkar https://www.youtube.com/watch?v=cYkmfk_y5DE

****** Ερώτηση / Άσκηση:
Πώς ένα κυκλικό μοτίβο μετατοπίζεται σε διαφορά φάσης σε σχέση με ένα άλλο μοτίβο; Παρουσιάστε την έννοια της μετατόπισης φάσης σε μετρικά μοτίβα.

***** Passacaglia.

Εντυπωσιακό παράδειγμα passacaglia με χρήση μόνο ενός θέματος/υπόβαθρου 4 νοτών:
BIBER PASSACAGLIA - Elicia Silverstein, βιολιστής https://www.youtube.com/watch?v=sgcR183f8gA

***** Manjul Bhargava σχετικά με τη μετρική κωδικοποίηση "yamātārājabhānasalagā"

Διεθνές συνέδριο για το μηδέν: Τα μαθηματικά στην ινδική μουσική
https://youtu.be/wSIu11HxkdY?t=2230

Άσκηση: Βρείτε τα αρχαία ελληνικά ονόματα των 8 3-σύλλαβων μοτίβων που κωδικοποιούνται από το yamātārājabhānasalagā
Άσκηση/ερωτήσεις:
- Σε ποιο βαθμό κατά τη γνώμη σας μπορεί να χρησιμοποιηθεί μια τέτοια μέθοδος κωδικοποίησης μετρικών μοτίβων ως ένα είδος προφορικής σημειογραφίας για μουσικά κομμάτια;
- Σε ποιο βαθμό φαντάζεστε ότι χρησιμοποιείται στην παραδοσιακή ινδική μουσική;
- Με ποιον τρόπο υποθέτετε ότι θα μπορούσαν τέτοιες αρχές μετρικής κωδικοποίησης να χρησιμοποιηθούν ως τεχνικές σημειογραφίας στη σύγχρονη μουσική και στη σύγχρονη τέχνη;
- Υπάρχουν ανάλογα μοτίβα ή/και τεχνικές κατασκευής και σχεδιασμού στις εικαστικές τέχνες;
* Session 2: (250307): Algorithms, Cycles and Fluxus Scores in Avant-garde music

Starting point:  György Ligeti, "Poème symphonique" for 100 Metronomes

#+begin_quote
Poème symphonique is a 1962 composition by György Ligeti for one hundred mechanical metronomes. It was written during his brief acquaintance with the Fluxus movement.

The piece requires ten "performers", each one responsible for ten of the hundred metronomes. The metronomes are set up on the performance platform, and they are then all wound to their maximum extent and set to different speeds. Once they are all fully wound, there is a silence of two to six minutes, at the discretion of the conductor; then, at the conductor's signal, all of the metronomes are started as simultaneously as possible. The performers then leave the stage. As the metronomes wind down one after another and stop, periodicity becomes noticeable in the sound, and individual metronomes can be more clearly distinguished. The piece typically ends with just one metronome ticking alone for a few beats, followed by silence, and then the performers return to the stage.
#+end_quote

A performance of this piece can be seen at:
https://www.youtube.com/watch?v=NBF7QWmSOKo&ab_channel=FracFranche-Comt%C3%A9


In this session, we program a port of this score to the SuperCollider environment. We examine the algorithmic potential of the score and its sonic behavior.

** Part 1: A port of the piece in sccode.org

First we examine a port by Ali Balighi published in [[https://sccode.org/1-5ir][sccode.org]]
(Copied in the present repository as: [[file:Code/Code_250307/Metronome_sccode.scd][Metronome from sccode]])


* Footnotes
