#+title: Week4 250317

* Θέμα: Έρως (Στην Ανθρωπολογία, Ποίηση και τη Μουσική)

* Ανθρωπολογία / Μυθολογία
** Holi Festival (Ινδία)

#+begin_quote
In 2025, Holi, the festival of colors, will be celebrated on March 17. The festival typically falls on the full moon day in the month of Phalguna in the Hindu calendar, which usually corresponds to late February or March in the Gregorian calendar.
#+end_quote

Holi Explained | The Hindu Festival of Colors
https://www.youtube.com/watch?v=FZ9ed-zDazk

The Story of Holi Festival | Why is Holi Celebrated | History of Holi | Pebbles Live
https://www.youtube.com/watch?v=wlAolivJAxM
** Inanna, Shamhat (Σουμερία)
** Αφροδίτη, Ελένη (Μικρά Ασία, Ελλάς)
* Ποίηση
** Tales of Ise: It is not the moon

#+begin_quote
月やあらぬ　春や昔の春ならぬ　わが身ひとつは　もとの身にして
#+end_quote

#+begin_quote
Δεν είναι το ίδιο φεγγάρι, δεν είναι η ίδια άνοιξη όπως παλιά; Μόνο εγώ είμαι ακόμα ο ίδιος όπως πριν.
#+end_quote

Ή:

#+begin_quote
"Δεν είναι το ίδιο φεγγάρι, ούτε η άνοιξη είναι η άνοιξη του παρελθόντος· μόνο εγώ παραμένω ο ίδιος όπως ήμουν."
#+end_quote

*** Interpretation from Izutsu:

#+begin_quote
“— Is this the same moon? Even in spring, it is no longer the spring of old... Ah, it is only I who remain unchanged from those days. I continue to think of that person. Is it that I can no longer return to the past...?”
#+end_quote

** Be my Baby in Babylonian

Andrew George | Be My Baby in Babylonia
https://www.youtube.com/watch?v=xYSqscmp_f0

** Άσμα Ασμάτων

*** Θεοτόκος Μαρία - Χαιρετισμοί (Χριστιανικός Μεσαίωνας, Δύση)

** Emily Dickinson: That I did always love

https://allpoetry.com/That-I-did-always-love

[That I did always love](https://allpoetry.com/That-I-did-always-love)
549

See also: https://bloggingdickinson.blogspot.com/2019/07/that-i-did-always-love.html

#+begin_quote
That I did always love
I bring thee Proof
That till I loved
I never lived—Enough—

That I shall love alway—
I argue thee
That love is life—
And life hath Immortality—

This—dost thou doubt—Sweet—
Then have I
Nothing to show
But Calvary—
#+end_quote

* Μουσική
** Nigra sum (Claudio Monteverdi, Vespro della Beata Vergine)

*** Monteverdi Vespers (2/8) – Nigra sum – Jacob Perry, APOLLO'S FIRE
https://www.youtube.com/watch?v=sEnaystIygA

*** Monteverdi: Vespers for the Feast of Santa Barbara: XI. Nigra sum, sed formosa

https://www.youtube.com/watch?v=mgOVoCRet_8

*** Nigra Sum from Monteverdi's Marian Vespers by Dutch National Opera

https://www.youtube.com/watch?v=g4tNe9OFYUg
** Laeva eius amplexabitur me (Liturgical chant / Claudio Monteverdi, Vespro della Beata Vergine)
*** Vespers: Antiphon: Laeva eius sub capite meo
https://www.youtube.com/watch?v=DpEziDSIiDs

** You don't know what love is
*** Origins

#+begin_quote
The song was written by Don Raye (lyrics) and Gene de Paul (music) in 1941. It was initially composed for the film "The Tenth Avenue Angel," which was released in 1948, but it gained popularity in the jazz world before that.
#+end_quote

*** Chet Baker: You don't know what love is...
Chet Baker - You don't know what love is (1956) Live
https://www.youtube.com/watch?v=CgqVDeoEgko

#+begin_quote
You don't know what love is
Until you've learned the meaning of the blues
Until you've loved a love you had to loose
You don't know what love is

You don't know how lips hurt
Until you've kissed and had to pay the cost
Until you've flipped you're heart and you have lost
You don't know what love is

Do you know how a lost heart fears
The thought of reminiscing
And how lips have taste of tears
Loose the taste for kissing

You don't know how hearts burn
For love that cannot live, yet never dies
Until you've faced each dawn with sleepless eyes
You don't know what love is

You don't know how hearts burn
For love that cannot live, yet never dies
Until you've faced each dawn with sleepless eyes
How could you know what love is, what love is
What love is
#+end_quote
**** Τονίζοντας τους πρωτους στίχους κάθε στροφης
***** You don't know what love is
Until you've learned the meaning of the blues
Until you've loved a love you had to loose
You don't know what love is
***** You don't know how lips hurt
Until you've kissed and had to pay the cost
Until you've flipped you're heart and you have lost
You don't know what love is
***** Do you know how a lost heart fears
The thought of reminiscing
And how lips have taste of tears
Loose the taste for kissing
***** You don't know how hearts burn
For love that cannot live, yet never dies
Until you've faced each dawn with sleepless eyes
You don't know what love is
***** You don't know how hearts burn
For love that cannot live, yet never dies
Until you've faced each dawn with sleepless eyes
How could you know what love is, what love is
What love is
*** Nina Simone - You Don't Know What Love Is

https://www.youtube.com/watch?v=BguiWbW5j3Q
