#+title: Ada E7 Weekly Notes250223

* Session 2: 250307 Algorithms, Cycles and Fluxus Scores in Avant-garde music

Starting point:  György Ligeti, "Poème symphonique" for 100 Metronomes

#+begin_quote
Poème symphonique is a 1962 composition by György Ligeti for one hundred mechanical metronomes. It was written during his brief acquaintance with the Fluxus movement.

The piece requires ten "performers", each one responsible for ten of the hundred metronomes. The metronomes are set up on the performance platform, and they are then all wound to their maximum extent and set to different speeds. Once they are all fully wound, there is a silence of two to six minutes, at the discretion of the conductor; then, at the conductor's signal, all of the metronomes are started as simultaneously as possible. The performers then leave the stage. As the metronomes wind down one after another and stop, periodicity becomes noticeable in the sound, and individual metronomes can be more clearly distinguished. The piece typically ends with just one metronome ticking alone for a few beats, followed by silence, and then the performers return to the stage.
#+end_quote

A performance of this piece can be seen at:
https://www.youtube.com/watch?v=NBF7QWmSOKo&ab_channel=FracFranche-Comt%C3%A9

In this session, we program a port of this score to the SuperCollider environment. We examine the algorithmic potential of the score and its sonic behavior.

** Part 1: A port of the piece in sccode.org

*** Ali Balighi's port at sccode
Ali Balighi published a port of the Metronome piece score on online collection of SuperCollider at:  https://sccode.org/1-5ir

The same code is also found as a separate scd file in the present repository at: [[file:Code/Code_250307/01_Metronome_sccode.scd][Metronome file - sccode]]

This code is based on Ppar pattern player. The resulting sound is not clearly related to the expected sound from the score instructions
