#+title: Week3 250316


* Main Topic: Tropes in music and sound art

To consider: Tropes, tricks, rhetorical figures, and their use in creating musical forms and sound art.

- Layering
- Silence
- Fadein
- Crossfade
- Repetition
- Drone

* Introduction: Layering, Litany, Public Theatre and Collective/Communal action
** Layering. Litany. Orchestrated Ritual and Prayer

*** Claudio Monteverdi: Vespro de la Beata Vergine, "Sancta Maria, Ora pro Nobis"
Performance with score, by René Jacobs
Monteverdi: Vespro della Beata Vergine - 12. Sonata sopra Sancta Maria - René Jacobs
https://www.youtube.com/watch?v=wb3fpKA41b4

*** Charles Ives: "Putnam’s Camp" from Three Places in New England
https://www.youtube.com/watch?v=bnl9Wo3UexU

* Silence

** Starting point: John Cage, 4':33"

John Cage: https://en.wikipedia.org/wiki/John_Cage
4':33" https://en.wikipedia.org/wiki/4′33″
*** John Cage: 4'33'' / Petrenko · Berliner Philharmoniker
https://www.youtube.com/watch?v=AWVUp12XPpU
*** John Cage's 4'33" (a performance by William Marx)
https://www.youtube.com/watch?v=JTEFKFiXSx4
*** John Cage's 4'33'' explained: The music of silence
https://www.youtube.com/watch?v=7bGU9NTJlIo
*** Is John Cage's 4'33'' music?: Prof. Julian Dodd at TEDxUniversityOfManchester
https://www.youtube.com/watch?v=WTCVnKROlos
*** "12 Variations of John Cage's 4'33" by John Cage (score)
https://musescore.com/user/5745341/scores/5873183
** Essay: Silence, Sound Art and Postcolonial Media Theories
https://www.neme.org/texts/revisiting-inarticulacy

** First full bar of silence in a western score

J.S.Bach, Cantata BWV 106 "Gottes Zeit ist die allerbeste Zeit" (Actus tragicus)

https://en.wikipedia.org/wiki/Gottes_Zeit_ist_die_allerbeste_Zeit,_BWV_106

Performances:
*** Full performance
Bach - Cantata Gottes Zeit..., 'Actus Tragicus' BWV 106 - Van Veldhoven | Netherlands Bach Society
https://www.youtube.com/watch?v=xXMUpqSyJJo

*** Analysis with score and examples - Introducing silence

J. S. Bach, Actus Tragicus: Analysis
https://www.youtube.com/watch?v=E1IIaM_vXQc

** Hidden silences and surprize silences in classical and romantic music
*** Silence as Joke: Joseph Haydn, String Quartet in E-flat major, Op. 33, No. 2

https://www.youtube.com/watch?v=iZo9FoajL4A
Last movement: https://youtu.be/iZo9FoajL4A?t=831
** Echo

(Bellinni: La Sonnambula)

** Drone

Bellini: Norma
Wagner: Rheingold Overture

** Time stretching / Eterochronicity

Isorhythmic motets.
Bach: Matthaeus Passion,

