#+title: Week5 250324

* Topic: Impressionism

* Socioeconomic and technical origins

- Acrylic colors
- Rise of unemployment

* Theoretical and research tenents and ojectives

Reaction to Romanticism and Classicism, search of new theories and techniques.

- Moving away from emotion depiction and towards objecivism - or rather symbolism.
  - cf: Maurice Maeterlinck and symbolism
- Embrace and explore physical theories of sound and color synthesis and psychological / physicological theories of sound and color perception.
- Focus on objective depiction - research on object vs. stimulus vs, impression

* Musical Examples

** Frederic Chiu : "Reflections" (Piano Album)

Note the connotation of "Reflections" as thinking about and mirroring.
*** All pieces on YouTube

https://www.youtube.com/watch?v=J9rfBRlGx30&list=PLgq8s8PRAs1ndcYTEYf_-tP0UDdEAx8_7&ab_channel=FredericChiu-Topic

*** The Pieces

**** Maurice Ravel: Miroirs
1. Noctuelles (Νυχτοπεταλούδες / Σκωριοί)
   https://www.youtube.com/watch?v=J9rfBRlGx30&list=PLgq8s8PRAs1ndcYTEYf_-tP0UDdEAx8_7&ab_channel=FredericChiu-Topic
2. Oiseaux Tristes (Λυπητερά Πτηνά)
   https://www.youtube.com/watch?v=Wv_CsZh7KAo&list=PLgq8s8PRAs1ndcYTEYf_-tP0UDdEAx8_7&index=2&ab_channel=FredericChiu-Topic
3. Miroirs: III. Une barque sur l’océan (Μια βάρκα στον ωκεανό)
   https://www.youtube.com/watch?v=JDl8vXjBNFI&list=PLgq8s8PRAs1ndcYTEYf_-tP0UDdEAx8_7&index=4&ab_channel=FredericChiu-Topic
4. Alborada del Gracioso (Πρωϊνή Σερενάτα του παλιάτσου)
   https://www.youtube.com/watch?v=-wuXiHqnCoM&list=PLgq8s8PRAs1ndcYTEYf_-tP0UDdEAx8_7&index=5&ab_channel=FredericChiu-Topic
5. La vallée des cloches (Η Κοιλάδα με τις Καμπάνες)
   https://www.youtube.com/watch?v=paUBF7eCBbs&list=PLgq8s8PRAs1ndcYTEYf_-tP0UDdEAx8_7&index=6&ab_channel=FredericChiu-Topic

**** Abel Decaux: Clairs de Lune
1. Minuit Passe (Περασμένα Μεσάνυχτα)
2. La ruelle (Το σοκκάκι)
3. Le cimetière (Το νεκροταφείο)
4. La mer (Η Θάλασσα)


**** Arnold Schoenberg: Drei Klavierstücke op. 11


*** Comments on the pieces


** Claude Debussy: Preludes (Πρελούδια, Πρώτος και δεύτερος Τόμος), Images, Estampes

*** Claudio Array plays Claude Debussy (Preludes Books 1 and 2, Images, Estapes)
Playlist on Youtube:

https://www.youtube.com/playlist?list=PLg9gZGjgtLWqAREZB_sBxuztPJ0ypnasz




*** Arturo Benedetti Michelangeli: Claude Debussy, Preludes Book 1 (with Score)

https://www.youtube.com/watch?v=zL2ScCnzSPA&ab_channel=Gogo

* Exercise: Synthesise imitations of timbre and texture from the pieces using digial means (SuperCollider)
